//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Cartilla_Atencion = new HashSet<Cartilla_Atencion>();
            this.Comprobante_Pago = new HashSet<Comprobante_Pago>();
        }
    
        public int id_paciente { get; set; }
        public string nombre { get; set; }
        public string raza { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string color { get; set; }
        public int id_cliente { get; set; }
    
        public virtual ICollection<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Comprobante_Pago> Comprobante_Pago { get; set; }
    }
}
