//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PET_DBEntities : DbContext
    {
        public PET_DBEntities()
            : base("name=PET_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cartilla_Atencion> Cartilla_Atencion { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Comprobante_Examen> Comprobante_Examen { get; set; }
        public DbSet<Comprobante_Pago> Comprobante_Pago { get; set; }
        public DbSet<Detalle_Atencion> Detalle_Atencion { get; set; }
        public DbSet<Empleado> Empleadoes { get; set; }
        public DbSet<Equipo_Sede> Equipo_Sede { get; set; }
        public DbSet<Examen> Examen { get; set; }
        public DbSet<Paciente> Pacientes { get; set; }
        public DbSet<Sede> Sedes { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
