//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        public Sede()
        {
            this.Empleadoes = new HashSet<Empleado>();
            this.Equipo_Sede = new HashSet<Equipo_Sede>();
        }
    
        public int id_sede { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        public virtual ICollection<Equipo_Sede> Equipo_Sede { get; set; }
    }
}
